#pragma once

void test_sparse_bit_field_tracks_sparse_pages();
void test_sparse_bit_field_packed_and_bitwise_operations();
void test_vulkan_uniform_registry_tracks_dirty_values();
void test_renderer_template_uploads_alias_value();
void test_queue_shader_rendering_uploads_filtered_render_components();
void test_queue_shader_rendering_uploads_multiple_components();

void test_shared_render_jobs_group_by_unique_component();
void test_shared_sim_jobs_group_by_shared_alias();
void test_shared_render_jobs_require_only_one_shared_component();

void test_shader_component_bindings_create_uploads();
void test_shader_component_binding_redeclaration_updates_slot();
void test_shader_component_upload_requires_binding();

void test_rendering_helper_uses_shader_owned_bindings();
void test_rendering_helper_supports_shared_mesh_batches();

void test_ecs_tags_track_entities_and_cleanup();
void test_tag_pool_keeps_dense_entities();
void test_entities_can_be_created_with_tags();
void test_deferred_tag_changes_flush_after_wall();
void test_filtered_query_uses_tags_and_excludes();

void test_tagged_sim_job_filters_component_iteration();
void test_tagged_dirty_job_tracks_filtered_entity_count();
void test_tag_only_sim_job_iterates_tagged_entities();
void test_exclude_filters_in_sim_jobs();
void test_tagged_render_job_filters_render_iteration();
void test_exclude_filters_in_render_jobs();

void test_sparse_tuple_component_storage_accesses_components();
void test_archetype_registration_tracks_components();
void test_archetype_registration_merges_superset_groups();
void test_archetype_rows_track_partial_component_presence();
void test_archetype_component_removal_keeps_other_components();
void test_archetype_registration_migrates_existing_standalone_components();
void test_archetype_registration_rejects_incomplete_overlap();
void test_archetype_view_uses_tuple_pool_with_standalone_components();
void test_archetype_sim_job_mutates_tuple_components();
void test_archetype_view_of_iterates_requested_components();
void test_view_of_read_conflicts_with_nonbuffered_writer();
void test_view_of_can_be_used_in_component_job();
void test_view_of_const_multi_component_each();
void test_archetype_render_transfer_uses_tuple_pool_dirty_state();
void test_sim_archetype_does_not_create_render_archetype();
void test_explicit_render_archetype_transfers_and_renders();
void test_direct_mutable_view_marks_components_dirty();
void test_render_archetype_registration_migrates_existing_render_sparse_pool();
void test_render_archetype_registration_preserves_pending_sparse_publish();

void test_component_type_ids_are_stable_and_distinct();
void test_processor_can_use_separate_simulation_and_render_pools();
void test_buffered_write_write_conflict();
void test_buffered_read_write_is_allowed();
void test_nonbuffered_read_write_conflict();
void test_view_cache_invalidates_on_storage_changes();
void test_dirty_entity_render_transfer_preserves_unchanged_entities();
void test_buffered_simulation_write_transfers_to_render();
void test_unwritten_buffered_pool_does_not_swap_on_unrelated_wall();
void test_dirty_threshold_promotes_to_full_transfer();
void test_dirty_wrapper_marks_only_touched_entities();
void test_dirty_wrapper_marks_only_touched_archetyped_entities();
void test_dirty_wrapper_marks_full_when_touched_count_reaches_threshold();
void test_global_dirty_wrapper_matches_namespaced_dirty_wrapper();
void test_structural_changes_are_deferred_until_wall_finishes();
void test_deferred_destroy_and_component_removal_are_invisible_until_wall_finishes();
void test_scheduler_logging();
