plugins { id 'com.android.application' }

android {
    namespace 'com.cppgameengine.mobile'
    compileSdk 35
    ndkVersion '27.2.12479018'

    defaultConfig {
        applicationId 'com.cppgameengine.mobile'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0'
        ndk { abiFilters 'arm64-v8a', 'x86_64' }
        externalNativeBuild {
            cmake {
                arguments '-DANDROID_STL=c++_static',
                    "-DSDL3_SOURCE_DIR=${file('../.deps/SDL').absolutePath}"
                cppFlags '-std=c++23'
            }
        }
    }
    sourceSets.main {
        java.srcDirs += [file('../.deps/SDL/android-project/app/src/main/java')]
        assets.srcDirs += [file('../../../examples'), file('../../build')]
    }
    externalNativeBuild { cmake { path file('../../CMakeLists.txt'); version '3.22.1' } }
    buildTypes { release { minifyEnabled false } }
}
